version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
  backend:
    build: ./server
    container_name: backend
    ports:
      - "3030:3030"
# services:
#   todo-app:
#     build:
#       context: ./app
#     links:
#       - todo-database
#     environment:
#       NODE_ENV: production
#     ports:
#       - 3000:3000

